[tool.poetry]
name = "fast-graphrag"
version = "0.0.4"
description = ""
authors = ["Luca Pinchetti <luca@circlemind.co>", "Antonio Vespoli <antonio@circlemind.co>", "Yuhang Song <yuhang@circlemind.co>"]
packages = [{include = "fast_graphrag" }]
readme = "README.md"

[tool.poetry.dependencies]
boto3 = "^1.35.93"
python = "^3.10"
igraph = "^0.11.6"
xxhash = "^3.5.0"
pydantic = "^2.9.2"
scipy = "^1.14.1"
scikit-learn = "^1.5.2"
tenacity = "^9.0.0"
openai = "^1.52.1"
scipy-stubs = "^1.14.1.5"
hnswlib = "^0.8.0"
instructor = {extras = ["anthropic"], version = "^1.7.2"}
requests = "^2.32.3"
python-dotenv = "^1.0.1"
tree-sitter = "^0.24.0"
tree-sitter-typescript = "^0.23.2"
tree-sitter-rust = "^0.23.2"


[tool.poetry.group.dev.dependencies]
ruff = "^0.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4",  # flake8-comprehensions
    "N",  # PEP8 naming convetions
    "D"  # pydocstyle
]
ignore = [
    "C901",  # too complex
    "W191",  # indentation contains tabs
    "D401"  # imperative mood
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"_prompt.py" = ["E501"]

[tool.poetry.scripts]
test-app = "fast_graphrag.test:start"
analyse-code = "fast_graphrag.analyse-code:main"
repo-map = "fast_graphrag.repo-map:main"
